services:
  mysql:
    image: mysql:8.3
    container_name: mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: electricity-business
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3366:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: ./
    container_name: app
    depends_on:
      - mysql
    restart: on-failure
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: electricity-business
      DB_USER: user
      DB_PASSWORD: password
    volumes:
      - ./exports:/app/exports

volumes:
  mysql_data:
